# Generated by Django 2.2.4 on 2019-09-03 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190903_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
